--- #YAML:1.0
name:                Class-Workflow
version:             0.02
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Moose:                         0.09_03
    Set::Object:                   0.15
    Test::More:                    0
    Test::use::ok:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
