# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Workflow
version:      0.01_03
version_from: lib/Class/Workflow.pm
installdirs:  site
requires:
    Moose:                         0.09_03
    Set::Object:                   0.15
    Test::More:                    0
    Test::use::ok:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
