--- #YAML:1.0
name:                Class-Workflow
version:             0.06
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Data::Compare:                 0
    Moose:                         0.17
    Set::Object:                   0.15
    Test::More:                    0
    Test::use::ok:                 0
    YAML::Syck:                    0.82
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
