--- #YAML:1.0
name:                Class-Workflow
version:             0.09
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Data::Compare:                 0
    Moose:                         0.37
    Set::Object:                   1.19
    Test::More:                    0
    Test::use::ok:                 0
    YAML::Syck:                    0.82
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
